[tox]
isolated_build = True
env_list = py310,py314
skipsdist = True

[flake8]
per-file-ignores = *:F405,F403
application_import_names = bin
import_order_style = google
max_line_length = 120
exclude = .venv,venv,.tox,.vscode,cleancorpus.egg-info

[testenv]
deps = 
    -rrequirements.txt
    pytest
    flake8
    pytest-timeout
commands = 
    pytest
    flake8
allowlist_externals = pytest
