[tox]
env_list = py31{0, 1, 2,3,4}

[testenv]
deps =
    pytest
commands =
    # Mysterious bug: pickle/dill can't serialize some internal object from a pytest call
    # This is fixed by disabling stdout/err capture...
    pytest -s