name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        tox
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install publishing dependencies
        if: github.ref == 'refs/heads/master'
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Install package dependencies
        if: github.ref == 'refs/heads/master'
        # Temporary duplication of the dependency list
        run: |
          python -m pip install docopt chardet nltk ftfy unidecode tqdm
      - name: Build and publish
        if: github.ref == 'refs/heads/master'
        env:
          TWINE_USERNAME: fbda
          TWINE_PASSWORD: ${{ secrets.PYPI_FBDA_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
